<?php
$dx_keys = array(
	'95 96 f8 09  8b df 8a 92  2b 15 40 be',  // rks trial , rks fs trial
	'ac 36 e2 88  9a de 96 32  3b 36 e1 8f',  // rks fs steam

	'ff ff ff ff  ff ff ff ff  ff ff ff ff',  // varpg trial , varpg2 trial
	'9d f6 e5 c8  8b ce 90 12  9b 0b f0 a3',  // viocide trial

	'f0 35 6b 1c  fb 9b ed 1d  03 70 e3 2d',  // eins
	'b3 9d a0 84  d7 37 53 1f  f1 08 18 80',  // zonzon

	//'',  //
);
